#!/usr/bin/env python3
"""Generate word JSON files with hints for the quack word pool.

Run from the repo root:
  python3 scripts/gen_word_hints.py
"""

import json
import os

# ---------------------------------------------------------------------------
# EN words with hints
# ---------------------------------------------------------------------------

EN_FOOD = [
    {"word": "pizza", "hints": ["round and flat", "often delivered", "Italian dish"]},
    {"word": "sushi", "hints": ["Japanese cuisine", "wrapped in seaweed", "served with ginger"]},
    {"word": "burger", "hints": ["between two buns", "often served with fries", "fast food classic"]},
    {"word": "pasta", "hints": ["Italian staple", "comes in many shapes", "served with sauce"]},
    {"word": "tacos", "hints": ["Mexican street food", "folded shell", "topped with salsa"]},
    {"word": "salad", "hints": ["mostly vegetables", "tossed with dressing", "considered healthy"]},
    {"word": "soup", "hints": ["served hot in a bowl", "liquid-based dish", "great for cold days"]},
    {"word": "sandwich", "hints": ["between two slices of bread", "portable meal", "endless filling options"]},
    {"word": "pancakes", "hints": ["flat and fluffy", "drizzled with syrup", "breakfast favorite"]},
    {"word": "waffles", "hints": ["grid-patterned surface", "often with butter", "breakfast or dessert"]},
    {"word": "steak", "hints": ["thick cut of meat", "cooked on a grill", "beef dish"]},
    {"word": "spaghetti", "hints": ["long thin pasta", "Italian classic", "often with meatballs"]},
    {"word": "ramen", "hints": ["Japanese noodle soup", "rich broth", "assorted toppings"]},
    {"word": "curry", "hints": ["spiced sauce dish", "from South Asia", "served over rice"]},
    {"word": "paella", "hints": ["Spanish rice dish", "cooked in a wide pan", "with seafood or chicken"]},
    {"word": "lasagna", "hints": ["layered pasta dish", "baked in the oven", "melted cheese on top"]},
    {"word": "risotto", "hints": ["creamy rice dish", "Italian cuisine", "slow-stirred"]},
    {"word": "omelette", "hints": ["folded egg dish", "cooked in a pan", "filled with cheese or veg"]},
    {"word": "croissant", "hints": ["buttery pastry", "crescent-shaped", "French bakery staple"]},
    {"word": "bagel", "hints": ["ring-shaped bread", "often toasted", "spread with cream cheese"]},
    {"word": "pretzel", "hints": ["twisted baked snack", "salty crust", "often dipped in mustard"]},
    {"word": "doughnut", "hints": ["ring-shaped fried dough", "covered in glaze or sprinkles", "sweet treat"]},
    {"word": "ice cream", "hints": ["frozen dessert", "comes in many flavors", "served in a cone"]},
    {"word": "cheesecake", "hints": ["rich creamy dessert", "cracker crust base", "topped with fruit"]},
    {"word": "brownie", "hints": ["dense chocolate square", "fudgy texture", "baked in a pan"]},
    {"word": "cookie", "hints": ["small baked sweet", "often has chocolate chips", "dunked in milk"]},
    {"word": "muffin", "hints": ["small domed cake", "often blueberry or banana", "breakfast treat"]},
    {"word": "cupcake", "hints": ["individual small cake", "piled with frosting", "eaten at parties"]},
    {"word": "apple pie", "hints": ["classic baked dessert", "fruit in pastry crust", "served warm"]},
    {"word": "chocolate", "hints": ["made from cocoa beans", "comes in bars", "dark, milk, or white"]},
    {"word": "popcorn", "hints": ["puffed corn kernels", "movie theater staple", "salted or buttered"]},
    {"word": "hot dog", "hints": ["sausage in a bun", "stadium food staple", "topped with mustard"]},
    {"word": "french fries", "hints": ["fried potato strips", "often with ketchup", "fast food side dish"]},
    {"word": "fried chicken", "hints": ["crispy battered poultry", "Southern comfort food", "juicy inside"]},
    {"word": "dumplings", "hints": ["filled dough pockets", "steamed or pan-fried", "Asian cuisine"]},
    {"word": "falafel", "hints": ["fried chickpea balls", "Middle Eastern street food", "served in pita"]},
    {"word": "hummus", "hints": ["chickpea-based dip", "spread on flatbread", "drizzled with olive oil"]},
    {"word": "guacamole", "hints": ["avocado-based dip", "Mexican condiment", "chunky or smooth"]},
    {"word": "bruschetta", "hints": ["toasted bread with topping", "Italian appetizer", "often with tomatoes"]},
    {"word": "tiramisu", "hints": ["Italian dessert", "coffee-soaked layers", "dusted with cocoa"]},
    {"word": "crepe", "hints": ["thin French pancake", "sweet or savory", "folded with fillings"]},
    {"word": "baguette", "hints": ["long French bread", "crispy crust", "bakery essential"]},
    {"word": "focaccia", "hints": ["flat Italian bread", "dimpled surface", "drizzled with olive oil"]},
    {"word": "pita", "hints": ["round flatbread", "hollow inside", "stuffed with fillings"]},
    {"word": "kebab", "hints": ["meat on a skewer", "grilled over flame", "Middle Eastern dish"]},
    {"word": "nachos", "hints": ["tortilla chips with cheese", "Mexican snack", "topped with jalapeños"]},
    {"word": "wonton", "hints": ["thin-wrapped dumpling", "Chinese cuisine", "often in soup"]},
    {"word": "dim sum", "hints": ["small Chinese portions", "served in steamer baskets", "weekend brunch tradition"]},
    {"word": "spring roll", "hints": ["crispy rolled wrapper", "filled with vegetables", "Asian appetizer"]},
    {"word": "churros", "hints": ["fried dough sticks", "rolled in cinnamon sugar", "dipped in chocolate"]},
]

EN_ANIMALS = [
    {"word": "dog", "hints": ["loyal companion", "wags its tail", "barks"]},
    {"word": "cat", "hints": ["purrs when content", "chases mice", "lands on its feet"]},
    {"word": "elephant", "hints": ["largest land animal", "has a trunk", "never forgets"]},
    {"word": "giraffe", "hints": ["tallest living animal", "long spotted neck", "eats from treetops"]},
    {"word": "penguin", "hints": ["flightless bird", "lives in cold climates", "waddles when walking"]},
    {"word": "dolphin", "hints": ["highly intelligent marine mammal", "leaps above water", "uses echolocation"]},
    {"word": "eagle", "hints": ["bird of prey", "sharp talons", "keen eyesight"]},
    {"word": "lion", "hints": ["king of the savanna", "males have a mane", "roars loudly"]},
    {"word": "tiger", "hints": ["striped big cat", "solitary predator", "excellent swimmer"]},
    {"word": "bear", "hints": ["hibernates in winter", "loves honey", "very strong"]},
    {"word": "wolf", "hints": ["howls at the moon", "hunts in packs", "ancestor of dogs"]},
    {"word": "fox", "hints": ["clever and cunning", "bushy tail", "nocturnal hunter"]},
    {"word": "rabbit", "hints": ["long ears", "hops around", "loves carrots"]},
    {"word": "turtle", "hints": ["hard shell on its back", "moves very slowly", "can live for a century"]},
    {"word": "parrot", "hints": ["colorful feathers", "can mimic speech", "lives in tropical forests"]},
    {"word": "owl", "hints": ["hunts at night", "can rotate its head", "hoots"]},
    {"word": "shark", "hints": ["apex ocean predator", "rows of sharp teeth", "dorsal fin above water"]},
    {"word": "whale", "hints": ["largest animal on Earth", "lives in the ocean", "breathes through a blowhole"]},
    {"word": "octopus", "hints": ["eight arms", "sprays ink", "can change color"]},
    {"word": "jellyfish", "hints": ["floats in the ocean", "no brain or bones", "can sting"]},
    {"word": "butterfly", "hints": ["colorful wings", "starts as a caterpillar", "sips flower nectar"]},
    {"word": "dragonfly", "hints": ["iridescent wings", "hovers over water", "eats mosquitoes"]},
    {"word": "bee", "hints": ["makes honey", "lives in a hive", "important pollinator"]},
    {"word": "ant", "hints": ["extremely strong for its size", "lives in colonies", "tunnels underground"]},
    {"word": "ladybug", "hints": ["red with black spots", "considered good luck", "eats aphids"]},
    {"word": "flamingo", "hints": ["stands on one leg", "pink feathers", "lives near lagoons"]},
    {"word": "zebra", "hints": ["black and white stripes", "African plains animal", "related to horses"]},
    {"word": "panda", "hints": ["black and white bear", "eats bamboo", "from China"]},
    {"word": "koala", "hints": ["clings to eucalyptus trees", "sleeps most of the day", "from Australia"]},
    {"word": "kangaroo", "hints": ["carries young in a pouch", "hops on powerful legs", "from Australia"]},
    {"word": "crocodile", "hints": ["ancient reptile", "lurks in rivers", "powerful jaw"]},
    {"word": "chameleon", "hints": ["changes color", "eyes move independently", "long sticky tongue"]},
    {"word": "peacock", "hints": ["spectacular tail fan", "brilliant blue plumage", "loud call"]},
    {"word": "pelican", "hints": ["large beak pouch", "scoops fish from water", "coastal bird"]},
    {"word": "starfish", "hints": ["five arms", "lives on the sea floor", "can regrow limbs"]},
    {"word": "crab", "hints": ["walks sideways", "hard shell", "pincers"]},
    {"word": "lobster", "hints": ["large claws", "red when cooked", "lives on the ocean floor"]},
    {"word": "seahorse", "hints": ["males carry young", "swims upright", "wraps tail around seaweed"]},
    {"word": "cheetah", "hints": ["fastest land animal", "black tear-stripe markings", "sprints in short bursts"]},
    {"word": "gorilla", "hints": ["largest primate", "knuckle walks", "lives in mountain forests"]},
    {"word": "toucan", "hints": ["enormous colorful beak", "tropical bird", "eats fruit"]},
    {"word": "sloth", "hints": ["moves extremely slowly", "hangs upside down", "sleeps most of the day"]},
    {"word": "hedgehog", "hints": ["covered in spines", "rolls into a ball", "nocturnal"]},
    {"word": "raccoon", "hints": ["masked face markings", "washes food in water", "nocturnal scavenger"]},
    {"word": "squirrel", "hints": ["bushy tail", "collects nuts", "climbs trees"]},
    {"word": "deer", "hints": ["males have antlers", "grazes in forests", "very graceful"]},
    {"word": "moose", "hints": ["largest member of the deer family", "broad flat antlers", "wades in lakes"]},
    {"word": "camel", "hints": ["humps store energy", "survives in the desert", "spits when annoyed"]},
    {"word": "otter", "hints": ["holds hands while sleeping", "cracks shells on its belly", "playful water mammal"]},
    {"word": "platypus", "hints": ["duck bill and beaver tail", "lays eggs", "venomous spurs on hind legs"]},
]

EN_PLACES = [
    {"word": "beach", "hints": ["sand between your toes", "waves crash ashore", "sun, sea and sandcastles"]},
    {"word": "mountain", "hints": ["snow-capped peaks", "hikers climb trails", "above the clouds"]},
    {"word": "forest", "hints": ["tall trees block sunlight", "animals hide in the undergrowth", "smells like pine"]},
    {"word": "desert", "hints": ["vast sandy dunes", "scorching heat by day", "very little rain"]},
    {"word": "volcano", "hints": ["erupts with lava", "cone-shaped mountain", "creates new land"]},
    {"word": "castle", "hints": ["medieval stone fortress", "surrounded by a moat", "towers and battlements"]},
    {"word": "lighthouse", "hints": ["tall tower by the sea", "flashing light guides ships", "warns of rocks"]},
    {"word": "cave", "hints": ["dark underground hollow", "stalactites hang from the ceiling", "bats live inside"]},
    {"word": "waterfall", "hints": ["water tumbles over a cliff", "creates a rainbow mist", "roaring sound"]},
    {"word": "island", "hints": ["surrounded by water", "reached by boat or plane", "isolated from the mainland"]},
    {"word": "city", "hints": ["skyscrapers and busy streets", "millions of people", "never sleeps"]},
    {"word": "village", "hints": ["small close-knit community", "few hundred residents", "quaint and quiet"]},
    {"word": "farm", "hints": ["crops and livestock", "red barns and silos", "early morning starts"]},
    {"word": "market", "hints": ["stalls selling fresh produce", "bustling with haggling", "colorful and loud"]},
    {"word": "library", "hints": ["shelves full of books", "whisper-quiet inside", "borrow and return"]},
    {"word": "stadium", "hints": ["packed with cheering fans", "grass pitch in the middle", "giant floodlights"]},
    {"word": "museum", "hints": ["exhibits behind glass", "ancient artifacts", "learn history"]},
    {"word": "airport", "hints": ["planes take off and land", "passport control", "departure gates"]},
    {"word": "train station", "hints": ["platforms and tracks", "timetables on the board", "whistle and steam"]},
    {"word": "bridge", "hints": ["spans a river or valley", "connects two sides", "cables or arches"]},
    {"word": "harbor", "hints": ["boats moored at docks", "protected bay", "smell of sea and fish"]},
    {"word": "park", "hints": ["green open space", "benches and paths", "dogs and picnics"]},
    {"word": "garden", "hints": ["flowers and vegetables", "neatly trimmed hedges", "watered every day"]},
    {"word": "canyon", "hints": ["steep rocky walls", "river carved the valley", "stunning red rock"]},
    {"word": "glacier", "hints": ["slow-moving river of ice", "found near the poles", "melting due to warming"]},
    {"word": "rainforest", "hints": ["dense canopy of trees", "incredibly biodiverse", "constant warm rain"]},
    {"word": "savanna", "hints": ["open grassland in Africa", "home to big game", "dry season turns yellow"]},
    {"word": "tundra", "hints": ["frozen treeless plains", "permafrost underground", "extreme cold winds"]},
    {"word": "cliff", "hints": ["sheer vertical rock face", "dramatic coastal drop", "seabirds nest on ledges"]},
    {"word": "fjord", "hints": ["deep narrow sea inlet", "steep mountain walls", "found in Scandinavia"]},
    {"word": "swamp", "hints": ["waterlogged muddy ground", "cypress trees", "alligators lurk"]},
    {"word": "meadow", "hints": ["open grassy field", "wildflowers bloom", "butterflies flutter"]},
    {"word": "vineyard", "hints": ["rows of grapevines", "harvested in autumn", "wine is made here"]},
    {"word": "orchard", "hints": ["fruit trees in rows", "blossom in spring", "picked in harvest season"]},
    {"word": "observatory", "hints": ["large domed telescope", "star-gazing at night", "astronomers work here"]},
    {"word": "cathedral", "hints": ["towering gothic spires", "stained glass windows", "centuries of worship"]},
    {"word": "palace", "hints": ["grand royal residence", "ornate architecture", "surrounded by formal gardens"]},
    {"word": "pyramid", "hints": ["triangular stone structure", "ancient burial monument", "in Egypt or Mexico"]},
    {"word": "ruins", "hints": ["crumbling ancient walls", "archaeologists dig here", "nature reclaims the stones"]},
    {"word": "aquarium", "hints": ["fish swim behind glass", "sharks glide overhead", "guided by dim blue light"]},
    {"word": "zoo", "hints": ["animals from around the world", "children feed giraffes", "conservation mission"]},
    {"word": "amusement park", "hints": ["rollercoasters and rides", "cotton candy and balloons", "screaming with joy"]},
    {"word": "shopping mall", "hints": ["shops under one roof", "food court in the middle", "air-conditioned"]},
    {"word": "skyscraper", "hints": ["glass and steel tower", "hundreds of floors up", "city skyline landmark"]},
    {"word": "tunnel", "hints": ["underground passage", "cars or trains pass through", "dark inside"]},
    {"word": "windmill", "hints": ["turning sails catch the wind", "grinds grain traditionally", "Dutch countryside icon"]},
    {"word": "barn", "hints": ["houses animals in winter", "hay stored in the loft", "big red wooden doors"]},
    {"word": "cemetery", "hints": ["headstones in neat rows", "peaceful and solemn", "final resting place"]},
    {"word": "greenhouse", "hints": ["glass walls and roof", "plants grow year-round", "humid and warm inside"]},
    {"word": "quarry", "hints": ["stone blasted from the earth", "open-pit excavation", "huge trucks haul rock"]},
]

EN_MOVIES = [
    {"word": "Frozen", "hints": ["princess with ice powers", "animated Disney musical", "Let it go"]},
    {"word": "Shrek", "hints": ["lovable green ogre", "talking donkey sidekick", "fairy tale world"]},
    {"word": "Toy Story", "hints": ["toys come alive when alone", "cowboy doll and space ranger", "Pixar classic"]},
    {"word": "The Lion King", "hints": ["circle of life", "young lion prince", "Hakuna Matata"]},
    {"word": "Finding Nemo", "hints": ["clownfish father's ocean quest", "just keep swimming", "blue tang companion"]},
    {"word": "Up", "hints": ["old man flies house with balloons", "young scout tags along", "adventure is out there"]},
    {"word": "Wall-E", "hints": ["robot collects trash on Earth", "falls in love with sleek robot", "futuristic animated film"]},
    {"word": "Coco", "hints": ["Day of the Dead setting", "boy visits land of the dead", "family and music"]},
    {"word": "Moana", "hints": ["Polynesian girl sails the ocean", "demigod Maui", "restores heart of Te Fiti"]},
    {"word": "Tangled", "hints": ["princess with very long hair", "trapped in a tower", "lantern festival"]},
    {"word": "Encanto", "hints": ["magical Colombian family", "everyone has a special gift", "Bruno we don't talk about"]},
    {"word": "Ratatouille", "hints": ["rat who loves cooking", "Paris restaurant setting", "anyone can cook"]},
    {"word": "Brave", "hints": ["Scottish princess with curly hair", "bear transformation", "archery competition"]},
    {"word": "Bambi", "hints": ["fawn in the forest", "mother's death scene", "classic Disney tearjerker"]},
    {"word": "Pinocchio", "hints": ["puppet who wants to be real", "nose grows when he lies", "cricket is his conscience"]},
    {"word": "Cinderella", "hints": ["glass slipper", "fairy godmother", "turns back to rags at midnight"]},
    {"word": "Aladdin", "hints": ["magic lamp genie", "flying carpet ride", "street boy becomes prince"]},
    {"word": "Mulan", "hints": ["Chinese girl disguises as soldier", "dragon Mushu", "honor your family"]},
    {"word": "Zootopia", "hints": ["city of anthropomorphic animals", "bunny cop and fox partner", "try everything"]},
    {"word": "Monsters Inc", "hints": ["monsters scare children for power", "little girl called Boo", "scream factory"]},
    {"word": "Cars", "hints": ["cars with personalities race", "small town Radiator Springs", "rookie learns humility"]},
    {"word": "A Bug's Life", "hints": ["ant colony vs grasshoppers", "circus bugs to the rescue", "Pixar insect world"]},
    {"word": "Lilo and Stitch", "hints": ["alien crash-lands in Hawaii", "little girl adopts him as a dog", "ohana means family"]},
    {"word": "Wreck-It Ralph", "hints": ["video game villain wants to be hero", "glitch racing girl", "arcade setting"]},
    {"word": "Inside Out", "hints": ["emotions are personified characters", "girl moves to a new city", "Joy and Sadness adventure"]},
    {"word": "The Incredibles", "hints": ["superhero family hides their powers", "superheroes are banned", "no capes"]},
    {"word": "Madagascar", "hints": ["zoo animals lost in the wild", "penguins plot an escape", "I like to move it"]},
    {"word": "Kung Fu Panda", "hints": ["clumsy panda becomes a warrior", "Dragon Scroll is blank", "there is no secret ingredient"]},
    {"word": "Ice Age", "hints": ["woolly mammoth, sloth and saber-tooth team up", "acorn-obsessed squirrel", "prehistoric adventure"]},
    {"word": "Rio", "hints": ["rare blue macaw goes to Brazil", "can't fly at first", "Carnival setting"]},
    {"word": "Happy Feet", "hints": ["penguin dances instead of sings", "tap dancing in Antarctica", "finding his voice"]},
    {"word": "Grease", "hints": ["high school romance in the 50s", "leather-jacketed gang", "summer lovin'"]},
    {"word": "Home Alone", "hints": ["boy accidentally left behind", "defends house from burglars", "booby traps everywhere"]},
    {"word": "Elf", "hints": ["human raised by elves at the North Pole", "goes to New York", "Christmas comedy"]},
    {"word": "Jumanji", "hints": ["board game comes to life", "wild animals invade the suburbs", "you can only finish it if you win"]},
    {"word": "Matilda", "hints": ["gifted girl with awful parents", "telekinetic powers", "kind teacher Miss Honey"]},
    {"word": "Paddington", "hints": ["Peruvian bear in London", "loves marmalade sandwiches", "polite and adventurous"]},
    {"word": "Ghostbusters", "hints": ["team of ghost exterminators", "proton pack weapons", "who you gonna call"]},
    {"word": "Beetlejuice", "hints": ["mischievous ghost for hire", "say the name three times", "striped suit"]},
    {"word": "The Goonies", "hints": ["kids hunt for pirate treasure", "save their neighborhood", "Chunk does the truffle shuffle"]},
    {"word": "E.T.", "hints": ["stranded alien befriends a boy", "phone home", "glowing fingertip"]},
    {"word": "Back to the Future", "hints": ["time-traveling DeLorean car", "must get back to 1985", "88 miles per hour"]},
    {"word": "Jurassic Park", "hints": ["dinosaurs cloned from DNA", "theme park goes horribly wrong", "life finds a way"]},
    {"word": "Jaws", "hints": ["great white shark terrorizes a beach town", "bigger boat needed", "suspenseful two-note theme"]},
    {"word": "Rocky", "hints": ["underdog boxer trains hard", "runs up the steps", "Eye of the Tiger"]},
    {"word": "Forrest Gump", "hints": ["life is like a box of chocolates", "runs across America", "bench scene narration"]},
    {"word": "Titanic", "hints": ["ocean liner hits an iceberg", "ill-fated love story", "I'm king of the world"]},
    {"word": "Shrek 2", "hints": ["ogre meets the in-laws", "Far Far Away kingdom", "Fairy Godmother villain"]},
    {"word": "Despicable Me", "hints": ["supervillain adopts three orphan girls", "little yellow Minions", "shrink ray heist"]},
    {"word": "Minions", "hints": ["little yellow creatures seek a master", "before they met Gru", "banana"]},
]

EN_OBJECTS = [
    {"word": "umbrella", "hints": ["opens above your head in the rain", "collapsible metal frame", "protects from sun too"]},
    {"word": "bicycle", "hints": ["two wheels powered by pedals", "chain drive", "helmet recommended"]},
    {"word": "guitar", "hints": ["six strings plucked or strummed", "hollow wooden body", "held in the lap"]},
    {"word": "telescope", "hints": ["tube that magnifies distant objects", "points at the stars", "eyepiece at one end"]},
    {"word": "lantern", "hints": ["portable light with a handle", "glass panels protect the flame", "old-fashioned glow"]},
    {"word": "typewriter", "hints": ["mechanical keyboard stamps ink on paper", "carriage returns with a ding", "pre-computer writing tool"]},
    {"word": "anchor", "hints": ["heavy metal hook dropped to the sea floor", "keeps a boat in place", "tattooed on sailors"]},
    {"word": "backpack", "hints": ["straps over both shoulders", "carries school or hiking gear", "zipped compartments"]},
    {"word": "clock", "hints": ["shows hours and minutes", "ticks with each second", "hung on the wall or worn on the wrist"]},
    {"word": "mirror", "hints": ["reflects your image back", "glass with a silvered backing", "dressing table essential"]},
    {"word": "magnifying glass", "hints": ["curved lens makes things look bigger", "held up to the eye", "detectives love it"]},
    {"word": "key", "hints": ["fits a specific lock", "cut metal teeth", "on a ring with others"]},
    {"word": "candle", "hints": ["wax column with a wick", "flickering warm flame", "birthday cake topper"]},
    {"word": "scissors", "hints": ["two blades pivot together", "cuts paper or fabric", "handle loops for fingers"]},
    {"word": "hammer", "hints": ["heavy metal head on a handle", "drives nails into wood", "bangs and clangs"]},
    {"word": "ladder", "hints": ["rungs between two uprights", "leans against a wall", "used to reach high places"]},
    {"word": "rope", "hints": ["twisted fibers form a long cord", "ties, climbs, or lassoes", "also used in tug-of-war"]},
    {"word": "binoculars", "hints": ["two telescopes joined together", "held up to both eyes", "for birdwatching or sports"]},
    {"word": "camera", "hints": ["captures images through a lens", "press the shutter button", "develops or stores photos"]},
    {"word": "radio", "hints": ["receives broadcast signals", "tunes to a frequency", "no screen required"]},
    {"word": "trophy", "hints": ["awarded to the winner", "gold cup on a plinth", "displayed on a shelf"]},
    {"word": "globe", "hints": ["spherical map of the Earth", "spins on a tilted axis", "find any country on it"]},
    {"word": "crown", "hints": ["worn on the head of royalty", "jewels set in gold", "symbol of authority"]},
    {"word": "dice", "hints": ["six numbered faces", "rolled to decide a move", "used in board games"]},
    {"word": "puzzle", "hints": ["interlocking cardboard pieces", "image revealed when complete", "spreads across the table"]},
    {"word": "chess set", "hints": ["64 black and white squares", "32 pieces per side", "knight moves in an L-shape"]},
    {"word": "book", "hints": ["pages bound between covers", "stories or knowledge inside", "borrowed from a library"]},
    {"word": "map", "hints": ["flat diagram of an area", "dotted lines for borders", "X marks the spot"]},
    {"word": "bottle", "hints": ["narrow neck for pouring liquids", "sealed with a cap or cork", "glass or plastic"]},
    {"word": "jar", "hints": ["wide-mouthed glass container", "sealed with a twist-off lid", "stores jam or pickles"]},
    {"word": "bucket", "hints": ["open-topped cylindrical container", "carried by a handle", "used for water or sand"]},
    {"word": "broom", "hints": ["long handle with bristles at the bottom", "sweeps the floor", "witches ride them"]},
    {"word": "shovel", "hints": ["broad blade for digging earth", "long wooden handle", "gardening essential"]},
    {"word": "wheelbarrow", "hints": ["single front wheel", "carries heavy loads", "gardeners push it"]},
    {"word": "kite", "hints": ["flies on a string in the wind", "diamond or box-shaped", "tails help it balance"]},
    {"word": "balloon", "hints": ["rubber stretched over air or helium", "floats upward when filled with gas", "pops loudly"]},
    {"word": "drum", "hints": ["taut skin stretched over a cylinder", "beaten with sticks or hands", "keeps the rhythm"]},
    {"word": "trumpet", "hints": ["brass instrument with three valves", "bell-shaped opening", "plays a fanfare"]},
    {"word": "violin", "hints": ["four strings drawn with a bow", "tucked under the chin", "smallest of the orchestra strings"]},
    {"word": "flute", "hints": ["slender silver tube blown sideways", "holes covered by the fingers", "high, clear tone"]},
    {"word": "paintbrush", "hints": ["bristles on a handle", "loads with paint or watercolor", "various widths"]},
    {"word": "easel", "hints": ["tripod stand holding a canvas", "artist's work surface", "adjustable height"]},
    {"word": "calculator", "hints": ["electronic number cruncher", "solar or battery powered", "small enough to fit in a pocket"]},
    {"word": "telephone", "hints": ["makes voice calls over a wire or signal", "dial or keypad", "rings when someone calls"]},
    {"word": "microscope", "hints": ["magnifies tiny specimens", "slide placed under the lens", "used in laboratories"]},
    {"word": "hourglass", "hints": ["sand flows from top to bottom", "measures a fixed time", "flipped to start again"]},
    {"word": "abacus", "hints": ["beads slide along rods", "ancient counting tool", "still used in some schools"]},
    {"word": "suitcase", "hints": ["rigid or soft-sided luggage", "rolls on wheels", "packed for travel"]},
    {"word": "compass", "hints": ["needle always points north", "round dial with cardinal directions", "navigators rely on it"]},
    {"word": "surfboard", "hints": ["long flat board ridden on waves", "needs a leash around the ankle", "waxed for grip"]},
]

# ---------------------------------------------------------------------------
# IT words with hints
# ---------------------------------------------------------------------------

IT_FOOD = [
    {"word": "pizza", "hints": ["rotonda e piatta", "spesso consegnata a casa", "piatto italiano"]},
    {"word": "sushi", "hints": ["cucina giapponese", "avvolto nell'alga", "servito con zenzero"]},
    {"word": "hamburger", "hints": ["tra due panini", "spesso servito con patatine", "classico fast food"]},
    {"word": "pasta", "hints": ["piatto base italiano", "mille forme diverse", "servita con il sugo"]},
    {"word": "tacos", "hints": ["cibo di strada messicano", "guscio ripiegato", "condito con salsa"]},
    {"word": "insalata", "hints": ["prevalentemente verdure", "condita con olio", "considerata leggera"]},
    {"word": "zuppa", "hints": ["servita calda in una ciotola", "piatto liquido", "perfetta in inverno"]},
    {"word": "panino", "hints": ["tra due fette di pane", "pasto da asporto", "farciture infinite"]},
    {"word": "frittelle", "hints": ["piatte e soffici", "con sciroppo d'acero", "colazione preferita"]},
    {"word": "waffle", "hints": ["superficie a griglia", "spesso con burro", "colazione o dolce"]},
    {"word": "bistecca", "hints": ["fetta spessa di carne", "cotta alla griglia", "piatto di manzo"]},
    {"word": "spaghetti", "hints": ["pasta lunga e sottile", "classico italiano", "spesso con polpette"]},
    {"word": "ramen", "hints": ["zuppa di noodle giapponese", "brodo ricco", "vari condimenti"]},
    {"word": "curry", "hints": ["piatto con salsa speziata", "dall'Asia meridionale", "servito con il riso"]},
    {"word": "paella", "hints": ["piatto di riso spagnolo", "cotto in una padella larga", "con frutti di mare"]},
    {"word": "lasagna", "hints": ["pasta stratificata", "cotta al forno", "formaggio fuso in cima"]},
    {"word": "risotto", "hints": ["piatto di riso cremoso", "cucina italiana", "mescolato lentamente"]},
    {"word": "frittata", "hints": ["uova strapazzate in padella", "piatto italiano", "può avere ripieno"]},
    {"word": "croissant", "hints": ["pasta sfoglia burrosa", "forma di mezzaluna", "prodotto da forno francese"]},
    {"word": "bagel", "hints": ["pane a forma di ciambella", "spesso tostato", "con crema di formaggio"]},
    {"word": "pretzel", "hints": ["snack da forno intrecciato", "crosta salata", "da intingere nella senape"]},
    {"word": "ciambella", "hints": ["pasta fritta a forma di anello", "glassata o colorata", "dolce goloso"]},
    {"word": "gelato", "hints": ["dessert congelato", "tanti gusti diversi", "servito in cono o coppetta"]},
    {"word": "cheesecake", "hints": ["dolce cremoso", "base di biscotto", "guarnito con frutta"]},
    {"word": "brownie", "hints": ["quadratino denso al cioccolato", "texture fondente", "cotto in teglia"]},
    {"word": "biscotto", "hints": ["piccolo dolce cotto al forno", "spesso con gocce di cioccolato", "da inzuppare nel latte"]},
    {"word": "muffin", "hints": ["piccola torta a cupola", "spesso ai mirtilli", "colazione dolce"]},
    {"word": "cupcake", "hints": ["tortina individuale", "ricoperta di glassa", "per le feste"]},
    {"word": "crostata di mele", "hints": ["dolce da forno classico", "frutta in guscio di pasta", "servita calda"]},
    {"word": "cioccolata", "hints": ["fatta con cacao", "tavolette e praline", "fondente, al latte o bianca"]},
    {"word": "popcorn", "hints": ["chicchi di mais soffiati", "immancabile al cinema", "salati o al burro"]},
    {"word": "hot dog", "hints": ["salsiccia in un panino", "cibo da stadio", "con senape o ketchup"]},
    {"word": "patatine fritte", "hints": ["strisce di patate fritte", "spesso con ketchup", "contorno del fast food"]},
    {"word": "pollo fritto", "hints": ["pollo croccante e impanato", "piatto della tradizione americana", "succoso dentro"]},
    {"word": "ravioli", "hints": ["pasta ripiena", "di carne o ricotta", "tipici di molte regioni"]},
    {"word": "falafel", "hints": ["polpette di ceci fritte", "cibo di strada mediorientale", "servito nel pita"]},
    {"word": "hummus", "hints": ["crema di ceci", "spalmata sul pane piatto", "condita con olio"]},
    {"word": "guacamole", "hints": ["crema di avocado", "condimento messicano", "cremosa o in pezzi"]},
    {"word": "bruschetta", "hints": ["pane tostato con condimento", "antipasto italiano", "spesso con pomodoro"]},
    {"word": "tiramisù", "hints": ["dolce italiano", "strati imbevuti di caffè", "spolverato di cacao"]},
    {"word": "crêpe", "hints": ["sottile pancake francese", "dolce o salata", "ripiegata con farcitura"]},
    {"word": "baguette", "hints": ["pane lungo francese", "crosta croccante", "indispensabile in panetteria"]},
    {"word": "focaccia", "hints": ["pane piatto italiano", "superficie a fossette", "condita con olio d'oliva"]},
    {"word": "pita", "hints": ["pane piatto rotondo", "cavo all'interno", "riempito con ingredienti vari"]},
    {"word": "kebab", "hints": ["carne allo spiedo", "grigliata sulla fiamma", "piatto mediorientale"]},
    {"word": "nachos", "hints": ["chips di tortilla con formaggio", "snack messicano", "con jalapeños e salsa"]},
    {"word": "wonton", "hints": ["raviolo cinese sottile", "cucina cinese", "spesso in brodo"]},
    {"word": "dim sum", "hints": ["piccole porzioni cinesi", "servite in cestelli a vapore", "tradizione del brunch"]},
    {"word": "involtino primavera", "hints": ["involucro croccante fritto", "ripieno di verdure", "antipasto asiatico"]},
    {"word": "churros", "hints": ["bastoncini di pasta fritta", "ricoperti di cannella e zucchero", "da intingere nel cioccolato"]},
]

IT_ANIMALS = [
    {"word": "cane", "hints": ["fedele compagno", "scodinzola", "abbaia"]},
    {"word": "gatto", "hints": ["fa le fusa quando è contento", "caccia i topi", "cade sempre in piedi"]},
    {"word": "elefante", "hints": ["il più grande animale terrestre", "ha la proboscide", "non dimentica mai"]},
    {"word": "giraffa", "hints": ["l'animale più alto del mondo", "lungo collo maculato", "mangia dalle cime degli alberi"]},
    {"word": "pinguino", "hints": ["uccello che non vola", "vive nei climi freddi", "cammina dondolandosi"]},
    {"word": "delfino", "hints": ["mammifero marino intelligente", "salta fuori dall'acqua", "usa l'ecolocalizzazione"]},
    {"word": "aquila", "hints": ["rapace con artigli affilati", "vista acutissima", "simbolo di libertà"]},
    {"word": "leone", "hints": ["re della savana", "il maschio ha la criniera", "ruggisce forte"]},
    {"word": "tigre", "hints": ["felino a strisce", "predatore solitario", "ottimo nuotatore"]},
    {"word": "orso", "hints": ["va in letargo in inverno", "ama il miele", "molto forte"]},
    {"word": "lupo", "hints": ["ulula alla luna", "caccia in branco", "antenato del cane"]},
    {"word": "volpe", "hints": ["astuta e furba", "coda folta", "caccia di notte"]},
    {"word": "coniglio", "hints": ["orecchie lunghe", "saltella", "ama le carote"]},
    {"word": "tartaruga", "hints": ["guscio duro sulla schiena", "si muove lentamente", "può vivere cent'anni"]},
    {"word": "pappagallo", "hints": ["piume colorate", "imita la voce umana", "vive nelle foreste tropicali"]},
    {"word": "gufo", "hints": ["caccia di notte", "ruota la testa quasi completamente", "fa verso"]},
    {"word": "squalo", "hints": ["predatore apicale oceanico", "file di denti affilati", "pinna dorsale in superficie"]},
    {"word": "balena", "hints": ["l'animale più grande del pianeta", "vive nell'oceano", "respira con lo sfiatatoio"]},
    {"word": "polpo", "hints": ["otto tentacoli", "spruzza inchiostro", "può cambiare colore"]},
    {"word": "medusa", "hints": ["galleggia in mare", "senza cervello né ossa", "può pungere"]},
    {"word": "farfalla", "hints": ["ali variopinte", "inizia come bruco", "sorseggia il nettare dei fiori"]},
    {"word": "libellula", "hints": ["ali iridescenti", "libra sull'acqua", "mangia le zanzare"]},
    {"word": "ape", "hints": ["produce il miele", "vive nell'alveare", "importante impollinatrice"]},
    {"word": "formica", "hints": ["forza straordinaria per la sua taglia", "vive in colonie", "scava gallerie"]},
    {"word": "coccinella", "hints": ["rossa con puntini neri", "porta fortuna", "mangia gli afidi"]},
    {"word": "fenicottero", "hints": ["sta su una zampa", "piume rosa", "vive vicino alle lagune"]},
    {"word": "zebra", "hints": ["strisce bianche e nere", "animale delle savane africane", "parente del cavallo"]},
    {"word": "panda", "hints": ["orso bianco e nero", "mangia bambù", "originario della Cina"]},
    {"word": "koala", "hints": ["si aggrappa agli eucalipti", "dorme quasi tutto il giorno", "dall'Australia"]},
    {"word": "canguro", "hints": ["porta il cucciolo nel marsupio", "salta su zampe potenti", "dall'Australia"]},
    {"word": "coccodrillo", "hints": ["rettile antico", "si nasconde nei fiumi", "mascella potentissima"]},
    {"word": "camaleonte", "hints": ["cambia colore", "occhi indipendenti", "lingua lunga e appiccicosa"]},
    {"word": "pavone", "hints": ["coda a ruota spettacolare", "piume azzurre brillanti", "grido stridente"]},
    {"word": "pellicano", "hints": ["grande sacca sul becco", "pesca raccogliendo acqua", "uccello costiero"]},
    {"word": "stella marina", "hints": ["cinque braccia", "vive sul fondo del mare", "rigenera gli arti persi"]},
    {"word": "granchio", "hints": ["cammina di lato", "guscio duro", "chele"]},
    {"word": "aragosta", "hints": ["grandi chele", "diventa rossa cuocendo", "vive sul fondo del mare"]},
    {"word": "cavalluccio marino", "hints": ["il maschio porta i piccoli", "nuota in verticale", "si aggrappa con la coda"]},
    {"word": "ghepardo", "hints": ["animale terrestre più veloce", "macchie nere sul manto", "sprint brevi"]},
    {"word": "gorilla", "hints": ["il primate più grande", "cammina sulle nocche", "vive nelle foreste montane"]},
    {"word": "tucano", "hints": ["becco enorme e colorato", "uccello tropicale", "mangia frutti"]},
    {"word": "bradipo", "hints": ["si muove lentissimamente", "sta appeso a testa in giù", "dorme quasi tutto il giorno"]},
    {"word": "riccio", "hints": ["ricoperto di spine", "si arrotola a palla", "notturno"]},
    {"word": "procione", "hints": ["maschera sul muso", "lava il cibo nell'acqua", "nottambulo e onnivoro"]},
    {"word": "scoiattolo", "hints": ["coda folta", "raccoglie ghiande", "sale sugli alberi"]},
    {"word": "cervo", "hints": ["il maschio ha le corna", "pascola nei boschi", "molto elegante"]},
    {"word": "alce", "hints": ["il più grande cervide", "palchi larghi e piatti", "guada i laghi"]},
    {"word": "cammello", "hints": ["le gobbe immagazzinano energia", "sopravvive nel deserto", "sputa quando è irritato"]},
    {"word": "lontra", "hints": ["si tiene per mano dormendo", "spezza i gusci sulla pancia", "mammifero acquatico giocoso"]},
    {"word": "ornitorinco", "hints": ["becco da anatra e coda da castoro", "depone le uova", "speroni velenosi sulle zampe"]},
]

IT_PLACES = [
    {"word": "spiaggia", "hints": ["sabbia tra le dita dei piedi", "onde che si infrangono", "ombrelloni e sdraio"]},
    {"word": "montagna", "hints": ["cime innevate", "escursionisti sui sentieri", "sopra le nuvole"]},
    {"word": "foresta", "hints": ["alberi alti bloccano la luce", "animali tra gli arbusti", "profumo di resina"]},
    {"word": "deserto", "hints": ["vaste dune sabbiose", "caldo torrido di giorno", "pochissima pioggia"]},
    {"word": "vulcano", "hints": ["erutta lava", "montagna a forma di cono", "crea nuova terra"]},
    {"word": "castello", "hints": ["fortezza medievale in pietra", "circondato da un fossato", "torri e merlature"]},
    {"word": "faro", "hints": ["alta torre sul mare", "luce intermittente per le navi", "avverte degli scogli"]},
    {"word": "grotta", "hints": ["cavità sotterranea buia", "stalattiti dal soffitto", "i pipistrelli ci abitano"]},
    {"word": "cascata", "hints": ["l'acqua precipita dalla roccia", "arcobaleno nella nebbia", "suono fragoroso"]},
    {"word": "isola", "hints": ["circondata dall'acqua", "si raggiunge in barca o aereo", "isolata dalla terraferma"]},
    {"word": "città", "hints": ["grattacieli e strade trafficate", "milioni di abitanti", "non si ferma mai"]},
    {"word": "villaggio", "hints": ["piccola comunità unita", "poche centinaia di abitanti", "tranquillo e pittoresco"]},
    {"word": "fattoria", "hints": ["campi coltivati e bestiame", "fienili rossi", "si alzano all'alba"]},
    {"word": "mercato", "hints": ["bancarelle di prodotti freschi", "si contratta sul prezzo", "colorato e rumoroso"]},
    {"word": "biblioteca", "hints": ["scaffali pieni di libri", "silenzio assoluto", "si prende in prestito e si restituisce"]},
    {"word": "stadio", "hints": ["tifosi che esultano", "campo erboso al centro", "grandi riflettori"]},
    {"word": "museo", "hints": ["reperti esposti nelle teche", "antichi manufatti", "si impara la storia"]},
    {"word": "aeroporto", "hints": ["aerei decollano e atterrano", "controllo passaporti", "uscite d'imbarco"]},
    {"word": "stazione ferroviaria", "hints": ["binari e banchine", "orari sul tabellone", "fischio del treno"]},
    {"word": "ponte", "hints": ["attraversa un fiume o una valle", "collega due sponde", "cavi o archi"]},
    {"word": "porto", "hints": ["barche ormeggiate alle banchine", "baia protetta", "odore di mare e pesce"]},
    {"word": "parco", "hints": ["spazio verde aperto", "panchine e viali", "cani e picnic"]},
    {"word": "giardino", "hints": ["fiori e ortaggi", "siepi ben potate", "annaffiato ogni giorno"]},
    {"word": "canyon", "hints": ["pareti rocciose ripide", "il fiume ha scavato la valle", "roccia rossa spettacolare"]},
    {"word": "ghiacciaio", "hints": ["fiume di ghiaccio lento", "nelle regioni polari", "si scioglie con il riscaldamento"]},
    {"word": "foresta tropicale", "hints": ["chioma di alberi fitta", "biodiversità straordinaria", "piogge calde continue"]},
    {"word": "savana", "hints": ["praterie aperte africane", "casa della fauna selvatica", "stagione secca ingiallisce tutto"]},
    {"word": "tundra", "hints": ["pianure gelate senza alberi", "permafrost sotterraneo", "venti gelidi estremi"]},
    {"word": "scogliera", "hints": ["parete rocciosa verticale", "strapiombo sul mare", "uccelli marini nidificano sulle pareti"]},
    {"word": "fiordo", "hints": ["profonda insenatura marina stretta", "pareti di montagna ripide", "tipico della Scandinavia"]},
    {"word": "palude", "hints": ["terreno acquitrinoso e fangoso", "cipressi nell'acqua", "coccodrilli in agguato"]},
    {"word": "prato", "hints": ["campo erboso aperto", "fiorisce in primavera", "farfalle che svolazzano"]},
    {"word": "vigneto", "hints": ["filari di viti", "vendemmia in autunno", "qui si produce il vino"]},
    {"word": "frutteto", "hints": ["alberi da frutto in fila", "fiorisce in primavera", "raccolta nella stagione"]},
    {"word": "osservatorio", "hints": ["grande telescopio a cupola", "si osservano le stelle di notte", "ci lavorano gli astronomi"]},
    {"word": "cattedrale", "hints": ["guglie gotiche altissime", "vetrate colorate", "secoli di culto"]},
    {"word": "palazzo", "hints": ["grandiosa residenza reale", "architettura sontuosa", "circondato da giardini formali"]},
    {"word": "piramide", "hints": ["struttura triangolare in pietra", "antico monumento funerario", "in Egitto o in Messico"]},
    {"word": "rovine", "hints": ["muri antichi diroccati", "gli archeologi scavano", "la natura riprende il sopravvento"]},
    {"word": "acquario", "hints": ["pesci che nuotano dietro al vetro", "squali che scivolano sopra la testa", "luce azzurra tenue"]},
    {"word": "zoo", "hints": ["animali da tutto il mondo", "i bambini danno da mangiare alle giraffe", "missione di conservazione"]},
    {"word": "parco divertimenti", "hints": ["montagne russe e giostre", "zucchero filato e palloncini", "urla di gioia"]},
    {"word": "centro commerciale", "hints": ["negozi sotto un unico tetto", "food court al centro", "aria condizionata"]},
    {"word": "grattacielo", "hints": ["torre di vetro e acciaio", "centinaia di piani", "emblema dello skyline cittadino"]},
    {"word": "tunnel", "hints": ["passaggio sotterraneo", "auto o treni vi transitano", "buio dentro"]},
    {"word": "mulino a vento", "hints": ["pale che girano nel vento", "macinava il grano", "icona della campagna olandese"]},
    {"word": "fienile", "hints": ["ricovera gli animali in inverno", "fieno nel solaio", "grandi porte di legno rosso"]},
    {"word": "cimitero", "hints": ["lapidi in fila ordinate", "luogo silenzioso e solenne", "ultimo riposo"]},
    {"word": "serra", "hints": ["pareti e tetto di vetro", "le piante crescono tutto l'anno", "umida e calda dentro"]},
    {"word": "cava", "hints": ["pietra estratta dalla terra", "scavo a cielo aperto", "enormi camion trasportano massi"]},
]

IT_MOVIES = [
    {"word": "Frozen", "hints": ["principessa con poteri di ghiaccio", "musical Disney animato", "Libera sono"]},
    {"word": "Shrek", "hints": ["simpatico orco verde", "asino parlante", "mondo fiabesco"]},
    {"word": "Toy Story", "hints": ["i giocattoli prendono vita", "cowboy e ranger spaziale", "classico Pixar"]},
    {"word": "Il re leone", "hints": ["cerchio della vita", "giovane principe leone", "Hakuna Matata"]},
    {"word": "Alla ricerca di Nemo", "hints": ["padre pesce clown attraversa l'oceano", "continua a nuotare", "compagna tartaruga blu"]},
    {"word": "Up", "hints": ["vecchio fa volare la casa con palloncini", "giovane scout a bordo", "là fuori c'è l'avventura"]},
    {"word": "Wall-E", "hints": ["robot raccoglie spazzatura sulla Terra", "si innamora di un robot futuristico", "film animato"]},
    {"word": "Coco", "hints": ["ambientato il Giorno dei Morti", "bambino visita la terra dei morti", "famiglia e musica"]},
    {"word": "Oceania", "hints": ["ragazza polinesiana naviga l'oceano", "semidio Maui", "restituisce il cuore di Te Fiti"]},
    {"word": "Rapunzel", "hints": ["principessa con i capelli lunghissimi", "rinchiusa in una torre", "festa delle lanterne"]},
    {"word": "Encanto", "hints": ["famiglia colombiana magica", "ognuno ha un dono speciale", "di Bruno non si parla"]},
    {"word": "Ratatouille", "hints": ["topo che ama cucinare", "ambientato a Parigi", "chiunque può cucinare"]},
    {"word": "Ribelle", "hints": ["principessa scozzese con capelli ricci", "trasformazione in orso", "gara di tiro con l'arco"]},
    {"word": "Bambi", "hints": ["cerbiatto nel bosco", "morte della madre", "classico Disney commovente"]},
    {"word": "Pinocchio", "hints": ["burattino che vuole diventare vero", "il naso cresce quando mente", "il grillo è la coscienza"]},
    {"word": "Cenerentola", "hints": ["scarpetta di cristallo", "fata madrina", "torna a essere stracciona a mezzanotte"]},
    {"word": "Aladdin", "hints": ["genio della lampada magica", "tappeto volante", "ragazzo di strada diventa principe"]},
    {"word": "Mulan", "hints": ["ragazza cinese si traveste da soldato", "drago Mushu", "onora la tua famiglia"]},
    {"word": "Zootropolis", "hints": ["città di animali antropomorfi", "coniglietta poliziotta e volpe", "prova tutto"]},
    {"word": "Monsters & Co.", "hints": ["i mostri spaventano i bambini per energia", "la piccola Boo", "fabbrica di urla"]},
    {"word": "Cars", "hints": ["macchine con personalità", "Radiator Springs", "rookie impara la lezione"]},
    {"word": "A Bug's Life", "hints": ["colonia di formiche contro le cavallette", "insetti circensi in soccorso", "mondo degli insetti Pixar"]},
    {"word": "Lilo & Stitch", "hints": ["alieno atterra alle Hawaii", "bambina lo adotta come cane", "ohana significa famiglia"]},
    {"word": "Ralph Spaccatutto", "hints": ["il cattivo del videogioco vuole essere eroe", "bambina glitch nelle gare", "ambientato nelle sale giochi"]},
    {"word": "Inside Out", "hints": ["le emozioni sono personaggi", "bambina si trasferisce in una nuova città", "Gioia e Tristezza in viaggio"]},
    {"word": "Gli Incredibili", "hints": ["famiglia di supereroi nasconde i poteri", "i supereroi sono vietati", "niente mantelli"]},
    {"word": "Madagascar", "hints": ["animali dello zoo persi allo stato brado", "i pinguini tramano la fuga", "mi piace muovermi"]},
    {"word": "Kung Fu Panda", "hints": ["panda goffo diventa guerriero", "il Rotolo del Drago è vuoto", "non c'è ingrediente segreto"]},
    {"word": "L'era glaciale", "hints": ["mammut, bradipo e tigre dai denti a sciabola", "lo scoiattolo ossessionato dalla ghianda", "avventura preistorica"]},
    {"word": "Rio", "hints": ["ara blu raro va in Brasile", "all'inizio non sa volare", "ambientato al Carnevale"]},
    {"word": "Happy Feet", "hints": ["pinguino balla invece di cantare", "tip tap in Antartide", "trova la sua voce"]},
    {"word": "Grease", "hints": ["storia d'amore negli anni '50", "gang in giacca di pelle", "quell'estate dell'amore"]},
    {"word": "Mamma ho perso l'aereo", "hints": ["bambino dimenticato a casa", "difende la casa dai ladri", "trappole ovunque"]},
    {"word": "Elf", "hints": ["umano cresciuto dagli elfi al Polo Nord", "arriva a New York", "commedia di Natale"]},
    {"word": "Jumanji", "hints": ["il gioco da tavolo prende vita", "animali selvatici invadono il sobborgo", "si può finire solo vincendo"]},
    {"word": "Matilda", "hints": ["bambina prodigio con genitori terribili", "poteri telecinetici", "la gentile maestra Honey"]},
    {"word": "Paddington", "hints": ["orso peruviano a Londra", "ama i panini alla marmellata", "educato e avventuroso"]},
    {"word": "Ghostbusters", "hints": ["squadra di cacciatori di fantasmi", "pistole a protoni", "chi chiami"]},
    {"word": "Beetlejuice", "hints": ["fantasma burlone a noleggio", "dire il nome tre volte", "vestito a righe"]},
    {"word": "I Goonies", "hints": ["ragazzi in cerca di un tesoro pirata", "salvare il quartiere", "il ballo del tartufo"]},
    {"word": "E.T.", "hints": ["alieno abbandonato adottato da un bambino", "telefono casa", "dito che si illumina"]},
    {"word": "Ritorno al futuro", "hints": ["DeLorean viaggia nel tempo", "tornare al 1985", "ottantotto miglia all'ora"]},
    {"word": "Jurassic Park", "hints": ["dinosauri clonati dal DNA", "il parco a tema va storto", "la vita trova una via"]},
    {"word": "Lo squalo", "hints": ["squalo bianco semina il panico", "ci vuole una barca più grande", "tema musicale in due note"]},
    {"word": "Rocky", "hints": ["pugile sfavorito si allena duro", "sale i gradini di corsa", "Eye of the Tiger"]},
    {"word": "Forrest Gump", "hints": ["la vita è come una scatola di cioccolatini", "attraversa l'America di corsa", "racconta dal sedile di una panchina"]},
    {"word": "Titanic", "hints": ["transatlantico colpisce un iceberg", "storia d'amore infelice", "sono il re del mondo"]},
    {"word": "Shrek 2", "hints": ["l'orco incontra i suoceri", "il regno di Gran Bosco", "la Fata Madrina è la cattiva"]},
    {"word": "Cattivissimo me", "hints": ["supervil lano adotta tre orfanelle", "i piccoli Minions gialli", "il furto del raggio restringitore"]},
    {"word": "Minions", "hints": ["creature gialle in cerca di un capo", "prima di incontrare Gru", "banana"]},
]

IT_OBJECTS = [
    {"word": "ombrello", "hints": ["si apre sopra la testa quando piove", "telaio metallico pieghevole", "protegge anche dal sole"]},
    {"word": "bicicletta", "hints": ["due ruote mosse dai pedali", "trasmissione a catena", "si indossa il casco"]},
    {"word": "chitarra", "hints": ["sei corde pizzicate o strimpellate", "cassa in legno", "suonata in grembo"]},
    {"word": "telescopio", "hints": ["tubo che ingrandisce gli oggetti lontani", "puntato verso le stelle", "oculare ad un'estremità"]},
    {"word": "lanterna", "hints": ["luce portatile con manico", "pannelli di vetro proteggono la fiamma", "bagliore antico"]},
    {"word": "macchina da scrivere", "hints": ["tastiera meccanica che imprime inchiostro", "carrello a capo con un ding", "strumento di scrittura pre-computer"]},
    {"word": "ancora", "hints": ["gancio pesante affondato sul fondo del mare", "tiene ferma la barca", "tatuata sui marinai"]},
    {"word": "zaino", "hints": ["spallacci su entrambe le spalle", "porta libri o attrezzatura da trekking", "scomparti con cerniera"]},
    {"word": "orologio", "hints": ["mostra ore e minuti", "ticchetta ad ogni secondo", "al muro o al polso"]},
    {"word": "specchio", "hints": ["riflette la propria immagine", "vetro con retro argentato", "indispensabile per truccarsi"]},
    {"word": "lente d'ingrandimento", "hints": ["lente curva che ingrandisce", "si avvicina all'occhio", "amata dai detective"]},
    {"word": "chiave", "hints": ["si inserisce in una serratura specifica", "denti metallici sagomati", "su un mazzo con altre"]},
    {"word": "candela", "hints": ["colonna di cera con uno stoppino", "fiamma tremolante e calda", "sulla torta di compleanno"]},
    {"word": "forbici", "hints": ["due lame su un fulcro", "taglia carta o tessuto", "manici ad anello per le dita"]},
    {"word": "martello", "hints": ["testa metallica pesante su un manico", "conficca chiodi nel legno", "fa rumore bum bum"]},
    {"word": "scala", "hints": ["pioli tra due montanti", "appoggiata al muro", "serve per raggiungere posti alti"]},
    {"word": "corda", "hints": ["fibre intrecciate formano un lungo cordone", "serve per legare, arrampicarsi o fare il lazo", "si usa anche nel tiro alla fune"]},
    {"word": "binocolo", "hints": ["due telescopi uniti", "avvicinato ad entrambi gli occhi", "per il birdwatching o lo sport"]},
    {"word": "fotocamera", "hints": ["cattura immagini attraverso un obiettivo", "si preme il pulsante di scatto", "stampa o salva le foto"]},
    {"word": "radio", "hints": ["riceve segnali in broadcast", "si sintonizza su una frequenza", "nessuno schermo"]},
    {"word": "trofeo", "hints": ["assegnato al vincitore", "coppa dorata su piedistallo", "esposto su uno scaffale"]},
    {"word": "mappamondo", "hints": ["mappa sferica della Terra", "ruota su un asse inclinato", "si trova ogni paese"]},
    {"word": "corona", "hints": ["indossata sul capo della regalità", "gemme incastonate nell'oro", "simbolo di autorità"]},
    {"word": "dado", "hints": ["sei facce numerate", "si lancia per decidere una mossa", "usato nei giochi da tavolo"]},
    {"word": "puzzle", "hints": ["pezzi di cartone che si incastrano", "immagine rivelata quando completo", "si stende sul tavolo"]},
    {"word": "scacchiera", "hints": ["64 caselle bianche e nere", "32 pezzi per lato", "il cavallo muove a L"]},
    {"word": "libro", "hints": ["pagine rilegare tra le copertine", "storie o conoscenza dentro", "preso in prestito in biblioteca"]},
    {"word": "mappa", "hints": ["diagramma piatto di un'area", "linee tratteggiate per i confini", "la X segna il posto"]},
    {"word": "bottiglia", "hints": ["collo stretto per versare liquidi", "tappata con un tappo o un sughero", "di vetro o plastica"]},
    {"word": "barattolo", "hints": ["contenitore in vetro a bocca larga", "chiuso con un coperchio avvitabile", "conserva marmellate o sottaceti"]},
    {"word": "secchio", "hints": ["contenitore cilindrico aperto in cima", "trasportato per un manico", "per l'acqua o la sabbia"]},
    {"word": "scopa", "hints": ["lungo manico con setole in basso", "spazza il pavimento", "le streghe ci volano sopra"]},
    {"word": "pala", "hints": ["lama larga per scavare la terra", "lungo manico di legno", "indispensabile in giardino"]},
    {"word": "carriola", "hints": ["ruota anteriore singola", "trasporta carichi pesanti", "il giardiniere la spinge"]},
    {"word": "aquilone", "hints": ["vola appeso a un filo nel vento", "forma a rombo o a scatola", "la coda lo stabilizza"]},
    {"word": "palloncino", "hints": ["gomma gonfiata ad aria o elio", "sale verso l'alto col gas", "scoppia con un forte bang"]},
    {"word": "tamburo", "hints": ["pelle tesa su un cilindro", "percosso con bacchette o mani", "tiene il ritmo"]},
    {"word": "tromba", "hints": ["strumento a fiato in ottone con tre pistoni", "padiglione a campana", "suona una fanfara"]},
    {"word": "violino", "hints": ["quattro corde sfregate con un archetto", "tenuto sotto il mento", "il più piccolo degli archi orchestrali"]},
    {"word": "flauto", "hints": ["sottile tubo d'argento soffiato di lato", "fori coperti dalle dita", "tono alto e cristallino"]},
    {"word": "pennello", "hints": ["setole su un manico", "carica acquerello o tempera", "varie larghezze"]},
    {"word": "cavalletto", "hints": ["treppiede che regge una tela", "piano di lavoro dell'artista", "altezza regolabile"]},
    {"word": "calcolatrice", "hints": ["dispositivo elettronico per i calcoli", "alimentata a energia solare o batteria", "sta in tasca"]},
    {"word": "telefono", "hints": ["effettua chiamate vocali via cavo o segnale", "quadrante o tastiera", "squilla quando arriva una chiamata"]},
    {"word": "microscopio", "hints": ["ingrandisce piccoli campioni", "il vetrino va sotto l'obiettivo", "usato in laboratorio"]},
    {"word": "clessidra", "hints": ["la sabbia scorre dall'alto verso il basso", "misura un tempo fisso", "si capovolge per ricominciare"]},
    {"word": "abaco", "hints": ["palline scorrono lungo le aste", "antico strumento di calcolo", "usato ancora in alcune scuole"]},
    {"word": "valigia", "hints": ["bagaglio rigido o morbido", "scorre su rotelle", "si riempie per viaggiare"]},
    {"word": "bussola", "hints": ["l'ago punta sempre a nord", "quadrante con i punti cardinali", "i navigatori la usano"]},
    {"word": "tavola da surf", "hints": ["tavola lunga e piatta per cavalcare le onde", "cordino alla caviglia", "cerata per l'aderenza"]},
]

# ---------------------------------------------------------------------------
# Write all JSON files
# ---------------------------------------------------------------------------

FILES = [
    ("public/words/en/food.json",    "en", "food",    EN_FOOD),
    ("public/words/en/animals.json", "en", "animals", EN_ANIMALS),
    ("public/words/en/places.json",  "en", "places",  EN_PLACES),
    ("public/words/en/movies.json",  "en", "movies",  EN_MOVIES),
    ("public/words/en/objects.json", "en", "objects", EN_OBJECTS),
    ("public/words/it/food.json",    "it", "food",    IT_FOOD),
    ("public/words/it/animals.json", "it", "animals", IT_ANIMALS),
    ("public/words/it/places.json",  "it", "places",  IT_PLACES),
    ("public/words/it/movies.json",  "it", "movies",  IT_MOVIES),
    ("public/words/it/objects.json", "it", "objects", IT_OBJECTS),
]

for path, lang, category, words in FILES:
    data = {
        "version": 1,
        "lang": lang,
        "category": category,
        "words": words,
    }
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"Wrote {len(words)} entries to {path}")
